development:
  adapter: postgresql
  database: db/development
  username: postgres
  password: 06and34
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: db/test
  username: postgres
  password: 06and34
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production
  username: postgres
  password: 06and34
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
cucumber:
  <<: *test